TYPO3:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Dotpulse.Accordion': ['NodeTypes/*']
    typoScript:
      autoInclude:
        'Dotpulse.Accordion': TRUE

Dotpulse:
  Accordion:
    includeCss: FALSE
    includeJavascript: FALSE
